import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  Compass, 
  Bot, 
  MapPin, 
  Calendar,
  MessageSquare,
  CreditCard,
  Shield,
  Sparkles,
  Users,
  Globe,
  HelpCircle,
  Mail,
  Phone,
  Clock
} from "lucide-react";

const features = [
  {
    icon: Bot,
    title: "AI-Powered Recommendations",
    description: "Get personalized travel suggestions based on your preferences, budget, and travel style using advanced machine learning algorithms."
  },
  {
    icon: MapPin,
    title: "Interactive Maps",
    description: "Explore destinations with our detailed interactive maps featuring real-time location data and points of interest."
  },
  {
    icon: Calendar,
    title: "Smart Itinerary Planning",
    description: "Create detailed day-by-day travel plans automatically generated by AI to optimize your travel experience."
  },
  {
    icon: MessageSquare,
    title: "Multilingual Chat Support",
    description: "Get 24/7 assistance in English, Hindi, Urdu, and Bengali from our AI-powered chat assistant."
  },
  {
    icon: CreditCard,
    title: "Secure Blockchain Payments",
    description: "Make payments safely using cryptocurrency, UPI, cards, or digital wallets with enterprise-grade security."
  },
  {
    icon: Shield,
    title: "Privacy & Security",
    description: "Your data is protected with 256-bit encryption and we never share your personal information with third parties."
  }
];

const stats = [
  { label: "Active Users", value: "10,000+", icon: Users },
  { label: "Destinations", value: "500+", icon: MapPin },
  { label: "Languages Supported", value: "4", icon: Globe },
  { label: "AI Conversations", value: "50,000+", icon: MessageSquare }
];

export function AboutSection() {
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center">
        <div className="flex items-center justify-center space-x-3 mb-4">
          <div className="w-12 h-12 gradient-hero rounded-xl flex items-center justify-center">
            <Compass className="h-6 w-6 text-white" />
          </div>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            TourismAI
          </h1>
        </div>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Your intelligent travel companion powered by artificial intelligence. Discover amazing destinations, 
          plan perfect itineraries, and explore the world like never before.
        </p>
      </div>

      {/* Mission Statement */}
      <Card className="bg-gradient-to-r from-primary/10 to-accent/10 border-primary/20">
        <CardContent className="p-8 text-center">
          <Sparkles className="h-12 w-12 text-primary mx-auto mb-4" />
          <h2 className="text-2xl font-bold mb-4">Our Mission</h2>
          <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
            To revolutionize travel planning through artificial intelligence, making personalized 
            travel experiences accessible to everyone. We believe that every journey should be unique, 
            memorable, and perfectly tailored to your dreams and preferences.
          </p>
        </CardContent>
      </Card>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <Card key={index} className="text-center hover:shadow-hover transition-all duration-300">
              <CardContent className="p-6">
                <Icon className="h-8 w-8 text-primary mx-auto mb-3" />
                <div className="text-2xl font-bold text-primary">{stat.value}</div>
                <p className="text-sm text-muted-foreground">{stat.label}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Features */}
      <div>
        <h2 className="text-3xl font-bold text-center mb-8">Why Choose TourismAI?</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card key={index} className="hover:shadow-hover transition-all duration-300">
                <CardHeader>
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
                      <Icon className="h-5 w-5 text-primary" />
                    </div>
                    <CardTitle className="text-lg">{feature.title}</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* How It Works */}
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl text-center">How TourismAI Works</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="text-center space-y-3">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                <span className="text-2xl font-bold text-primary">1</span>
              </div>
              <h3 className="font-semibold">Tell Us Your Preferences</h3>
              <p className="text-sm text-muted-foreground">Share your travel style, budget, and interests</p>
            </div>
            <div className="text-center space-y-3">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                <span className="text-2xl font-bold text-primary">2</span>
              </div>
              <h3 className="font-semibold">AI Analyzes & Recommends</h3>
              <p className="text-sm text-muted-foreground">Our AI finds perfect destinations and activities</p>
            </div>
            <div className="text-center space-y-3">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                <span className="text-2xl font-bold text-primary">3</span>
              </div>
              <h3 className="font-semibold">Plan Your Itinerary</h3>
              <p className="text-sm text-muted-foreground">Get detailed day-by-day travel plans</p>
            </div>
            <div className="text-center space-y-3">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                <span className="text-2xl font-bold text-primary">4</span>
              </div>
              <h3 className="font-semibold">Explore & Enjoy</h3>
              <p className="text-sm text-muted-foreground">Travel with confidence and AI assistance</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Contact & Support */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <HelpCircle className="h-5 w-5 text-primary" />
              <span>Need Help?</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="flex items-center space-x-3">
                <Mail className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="font-medium">Email Support</p>
                  <p className="text-sm text-muted-foreground">support@tourismAI.com</p>
                </div>
              </div>
              <div className="flex items-center space-x-3">
                <Phone className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="font-medium">Phone Support</p>
                  <p className="text-sm text-muted-foreground">+91 1800-123-456</p>
                </div>
              </div>
              <div className="flex items-center space-x-3">
                <Clock className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="font-medium">Support Hours</p>
                  <p className="text-sm text-muted-foreground">24/7 AI Chat, Mon-Fri 9AM-6PM Human Support</p>
                </div>
              </div>
            </div>
            
            <Button className="w-full">
              <MessageSquare className="mr-2 h-4 w-4" />
              Start Chat Support
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Frequently Asked Questions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h4 className="font-semibold mb-1">Is TourismAI free to use?</h4>
              <p className="text-sm text-muted-foreground">
                We offer a free basic plan with premium features available for subscribers.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-1">How accurate are AI recommendations?</h4>
              <p className="text-sm text-muted-foreground">
                Our AI uses real-time data and user feedback to provide 95%+ accurate recommendations.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-1">Can I use it offline?</h4>
              <p className="text-sm text-muted-foreground">
                Premium subscribers can download maps and itineraries for offline access.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-1">Which payment methods are accepted?</h4>
              <p className="text-sm text-muted-foreground">
                We accept cryptocurrency, UPI, cards, and major digital wallets.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Footer CTA */}
      <Card className="gradient-hero text-white">
        <CardContent className="p-8 text-center">
          <h2 className="text-2xl font-bold mb-4">Ready to Start Your AI-Powered Journey?</h2>
          <p className="text-white/90 mb-6 max-w-2xl mx-auto">
            Join thousands of travelers who are already exploring the world smarter with TourismAI. 
            Get personalized recommendations and create unforgettable memories.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" variant="secondary">
              <Compass className="mr-2 h-4 w-4" />
              Start Exploring Now
            </Button>
            <Button size="lg" variant="outline" className="border-white text-white hover:bg-white hover:text-primary">
              <MessageSquare className="mr-2 h-4 w-4" />
              Chat with AI Assistant
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}